In [2]:
import numpy as np

# case 1
# ex1 = np.array([1,2,3])
# ex2 = np.array([2,1,4])

# case 2
# ex1 = np.array([1,2,3,4])
# ex2 = np.array([3,2,1,5])

# case 3
ex1 = np.array([1,2,3,4,5])
ex2 = np.array([4,3,2,1,6])

# keep track of all OR nodes
orNodes = np.empty((0,3), int)

# find all OR nodes (aka any node in ex1 that is not in ex2 and visa versa)
def findOrNodes(ex1, ex2, orNodes):
    for i in ex1:
        if not np.isin(i, ex2):
            orNodes = np.append(orNodes,i)
    for i in ex2:
        if not np.isin(i, ex1):
            orNodes = np.append(orNodes,i)
    orNodes.sort()
    return orNodes

orNodes = findOrNodes(ex1,ex2, orNodes)
print("Or nodes: ")
print(orNodes)
print("Ex before or replacement: ")
print(ex2)

# replace OR nodes
def replaceOrNodes(ex, orNodes):
    for i in range(0,orNodes.size-1):
        ex = np.where(ex==orNodes[i+1], int(orNodes[i]), ex)
    return ex

ex2 = replaceOrNodes(ex2, orNodes)
print("Ex after or replacement: ")
print(ex2)

Or nodes: 
[5 6]
Ex before or replacement: 
[4 3 2 1 6]
Ex after or replacement: 
[4 3 2 1 5]


In [3]:
# initialize graph with first elements coming from 0 start node
graph = dict()
graph[0] = np.array([ex1[0],ex2[0]])

In [4]:
print("Initial graph: ")
print(graph)

Initial graph: 
{0: array([1, 4])}


In [5]:
# add each outgoing node from its previous root node
for i in range(0,ex1.size-1):
    if ex1[i] in graph:
        print(ex1[i])
        graph[ex1[i]] = np.append(graph[ex1[i]], ex1[i+1])
    else:
        graph[ex1[i]] = np.array(ex1[i+1])

In [6]:
print(graph)

{0: array([1, 4]), 1: array(2), 2: array(3), 3: array(4), 4: array(5)}


In [7]:
for i in range(0,ex2.size-1):
    if ex2[i] in graph:
        print(ex2[i])
        graph[ex2[i]] = np.append(graph[ex2[i]], ex2[i+1])
    else:
        graph[ex2[i]] = np.array(ex2[i+1])

4
3
2
1


In [8]:
print(graph)

{0: array([1, 4]), 1: array([2, 5]), 2: array([3, 1]), 3: array([4, 2]), 4: array([5, 3])}


In [9]:
andNodes = np.empty((0,2), int)

for key in graph:
    for i in graph[key]:
        if int(i) in graph:
            if key in graph[int(i)]:
                if key not in andNodes:
                    andNodes = np.concatenate((andNodes, [[i, key]]), axis=0)  

In [10]:
print(andNodes)

[[2 1]
 [4 3]]


In [11]:
from anytree import Node, RenderTree

In [12]:
print(orNodes)
orNodesList = list()
for i in range(0, orNodes.size-1,2):
    node = Node("OR")
    left = Node(orNodes[i], parent=node)
    right = Node(orNodes[i+1], parent=node)
    orNodesList.append(node)

[5 6]


In [13]:
for i in orNodesList:
    print(i.children)

print(orNodesList)

(Node('/OR/5'), Node('/OR/6'))
[Node('/OR')]


In [14]:
for i in orNodes:
    if i in andNodes:
        andNodes = andNodes[np.all(andNodes != i, axis=1)]

In [15]:
print(andNodes)

[[2 1]
 [4 3]]


In [16]:
print("Examples before merge:")
print(ex1)
print(ex2)

def mergeAnds(ex, andNodes):
    for i in andNodes:
        index = np.argwhere(ex==i[0])
        ex = np.delete(ex, index)
        index = np.argwhere(ex==i[0])
        ex = np.delete(ex, index)
    return ex

ex1 = mergeAnds(ex1, andNodes)
ex2 = mergeAnds(ex2, andNodes)

print("Examples after merge:")
print(ex1)
print(ex2)

Examples before merge:
[1 2 3 4 5]
[4 3 2 1 5]
Examples after merge:
[1 3 5]
[3 1 5]


In [17]:
andNodesList = list()
for j in andNodes:
    for i in range(0, j.size-1,2):
        node = Node("AND")
        left = Node(j[i], parent=node)
        right = Node(j[i+1], parent=node)
        andNodesList.append(node)

In [18]:
for i in andNodesList:
    print(i.children)

(Node('/AND/2'), Node('/AND/1'))
(Node('/AND/4'), Node('/AND/3'))


In [19]:
# ex1 = np.array([1,2,3,4,5])
# print(ex1)
# print(ex2)

# index = np.argwhere(ex1==andNodes[0][0])
# ex1 = np.delete(ex1, index)
# index = np.argwhere(ex1==andNodes[1][0])
# ex1 = np.delete(ex1, index)

# index = np.argwhere(ex2==andNodes[0][0])
# ex2 = np.delete(ex2, index)
# index = np.argwhere(ex2==andNodes[1][0])
# ex2 = np.delete(ex2, index)

In [20]:
for row in andNodes:
    for c in row:
        print(c)

2
1
4
3
